{% set name = "kvf" %}
{% set version = "0.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/kvf-{{ version }}.tar.gz
  sha256: f4885b1bbe66c8c20fdabe5cedeb3c0e5d12a54ac495f9e5fcf6fed0e0c51b73

build:
  entry_points:
    - kvf = kvf.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - paradict
    - braq

test:
  imports:
    - kvf
  commands:
    - pip check
    - kvf --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/pyrustic/kvf
  summary: The key-value file format with sections
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
